### ISSUE TITLE
Scripts are not 2FA compatible

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropy-procedures#95]
I needed to switch on 2FA, but it totally breaks the scripts in here:

```
kg:~/bsipocz/tegla2_mentes/munka/devel/atools/pr_consistency$ bash pr_checks.sh 
The repository this script currently works with is 'astropy/astropy'.

Enter your GitHub username and password so that API requests aren't as severely rate-limited...
Username: bsipocz
Password: 
Last modified date: 2018-08-01 14:59:47
Traceback (most recent call last):
  File "1.get_merged_prs.py", line 70, in <module>
    max_issues = repo.get_issues(state='closed', sort='created')[0].number
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/PaginatedList.py", line 40, in __getitem__
    self.__fetchToIndex(index)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/PaginatedList.py", line 58, in __fetchToIndex
    self._grow()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/PaginatedList.py", line 61, in _grow
    newElements = self._fetchNextPage()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/PaginatedList.py", line 163, in _fetchNextPage
    headers=self.__headers
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/Requester.py", line 169, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/github/Requester.py", line 182, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.TwoFactorException: 401 {'message': 'Must specify two-factor authentication OTP code.', 'documentation_url': 'https://developer.github.com/v3/auth#working-with-two-factor-authentication'}
```

As a workaround I suppose I can create a dummy user just to run the scripts (without providing a user the API rate limit is reached super quickly), but ideally we need to fix the scripts for this.

**Comment by astrofrog** [comment]
Yeah I ran into this yesterday too. It turns out a solution is to make a personal access token (which doesn't require 2FA) then use that instead of username/password
